import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/common/Footer'
import Navbar from '../components/common/Navbar'
import About from '../components/sections/About'
import Contact from '../components/sections/Contact'
import Header from '../components/sections/Header'
import Testimonial from '../components/sections/Testimonial'
import WorkArea from '../components/sections/WorkArea'
import Works from '../components/sections/Works'

import styled from 'styled-components'
import Modal from '../components/common/Modal'

const ModalWrapper = styled.div`
  /* min-height: 300px;
  width: 350px;
  background: #fff;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);

  .backdrop {
    background: rgba(0, 0, 0, .6);
    height: 100vh;
    width: 100vw;
    position: absolute;
    left: 0;
    top: 0;
  } */
`

const FormWrapper = styled.form`
   .form-group {
          display: flex;
          flex-direction: column;
          margin: 8px 0;
          label {
            font-size: 10px;
            font-weight: 600;
            margin-bottom: 3px;
          }
          input {
            border: none;
            background: #fff;
            height: 30px;
            width: 100%;
            @media(max-width: 768px) {
          width: 100%;
           
          }
          }
          textarea {
            width: 100%;
            height: 150px;
            border: none;
            background: #fff;
          }
        }
        button {
            border: none;
            padding: 8px 16px;
            font-size: 12px;
            font-weight: 500;
            cursor: pointer;
            background: #6896F3;
            color: #fff;
            margin-top: 1.4rem;
            border-radius: 4px;
        }
`

export default function Home() {
  const [showModal, setShowModal] = useState(false);
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setShowModal={setShowModal}/>
      <About />
      <Works />
      <WorkArea />
      <Testimonial />
      <Contact />
      <Footer />

     
        <Modal
          onClose={() => setShowModal(false)}
          show={showModal}
          title="Get Quote"
        >
         <FormWrapper>
           <div className="form-group">
             <label htmlFor="">First Name</label>
             <input type="text" />
           </div>
           <div className="form-group">
             <label htmlFor="">Last Name</label>
             <input type="text" />
           </div>
           <div className="form-group">
             <label htmlFor="">Email</label>
             <input type="email" />
           </div>
           <div className="form-group">
             <label htmlFor="">Message</label>
            <textarea></textarea>
           </div>
           <button>Send</button>
         </FormWrapper>
        </Modal>


       
    </div>
  )
}
